version: '3.1'

services:
  codrr_pg:
    image: postgres:15.1
    restart: always
    environment: 
    POSTGRES_DB: codrrdb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: root
volumes:
  - .db/init.sql:/docker-entrypoint-initdb.d/init.sql
ports:
  - 5432: 5432